// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sites.proto

package sites

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubType int32

const (
	SubType_SUB_TYPE_UNSPECIFIED SubType = 0
	SubType_OPERATOR             SubType = 1
	SubType_MATERIAL             SubType = 2
	SubType_TOOL                 SubType = 3
)

var SubType_name = map[int32]string{
	0: "SUB_TYPE_UNSPECIFIED",
	1: "OPERATOR",
	2: "MATERIAL",
	3: "TOOL",
}

var SubType_value = map[string]int32{
	"SUB_TYPE_UNSPECIFIED": 0,
	"OPERATOR":             1,
	"MATERIAL":             2,
	"TOOL":                 3,
}

func (x SubType) String() string {
	return proto.EnumName(SubType_name, int32(x))
}

func (SubType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b8d652432997d75, []int{0}
}

type Type int32

const (
	// TYPE_UNSPECIFIED is unspecified site.
	Type_TYPE_UNSPECIFIED Type = 0
	// CONTAINER is a non-discrete resource site, e.g. oil tank.
	Type_CONTAINER Type = 1
	// SLOT is a 1-1 resource site.
	Type_SLOT Type = 2
	// COLLECTION is a resource collection site.
	Type_COLLECTION Type = 3
	// QUEUE is a one-at-a-time resource site.
	Type_QUEUE Type = 4
	// COLQUEUE is a collection pipeline.
	Type_COLQUEUE Type = 5
)

var Type_name = map[int32]string{
	0: "TYPE_UNSPECIFIED",
	1: "CONTAINER",
	2: "SLOT",
	3: "COLLECTION",
	4: "QUEUE",
	5: "COLQUEUE",
}

var Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"CONTAINER":        1,
	"SLOT":             2,
	"COLLECTION":       3,
	"QUEUE":            4,
	"COLQUEUE":         5,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b8d652432997d75, []int{1}
}

type ActionType int32

const (
	ActionType_ADD    ActionType = 0
	ActionType_REMOVE ActionType = 1
)

var ActionType_name = map[int32]string{
	0: "ADD",
	1: "REMOVE",
}

var ActionType_value = map[string]int32{
	"ADD":    0,
	"REMOVE": 1,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}

func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b8d652432997d75, []int{2}
}

func init() {
	proto.RegisterEnum("sites.SubType", SubType_name, SubType_value)
	proto.RegisterEnum("sites.Type", Type_name, Type_value)
	proto.RegisterEnum("sites.ActionType", ActionType_name, ActionType_value)
}

func init() { proto.RegisterFile("sites.proto", fileDescriptor_9b8d652432997d75) }

var fileDescriptor_9b8d652432997d75 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xcf, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0xc5, 0x71, 0xda, 0x24, 0x6d, 0x7a, 0xf8, 0xd0, 0x95, 0xd5, 0x81, 0x95, 0x35, 0x03, 0x0b,
	0x4f, 0x60, 0xdc, 0x8b, 0x64, 0xc9, 0xcd, 0x0d, 0xc9, 0x35, 0x12, 0x0b, 0x95, 0x8a, 0x3a, 0x74,
	0x21, 0x15, 0x0d, 0x03, 0x6f, 0x8f, 0x6c, 0xd6, 0x8e, 0xff, 0xe5, 0x77, 0x74, 0x70, 0x7d, 0x3e,
	0x4e, 0x87, 0xf3, 0xe3, 0xe9, 0x7b, 0x9c, 0x46, 0x53, 0xe5, 0x68, 0x3c, 0x96, 0xc3, 0xcf, 0x5e,
	0x7f, 0x4f, 0x07, 0x73, 0x8f, 0xf5, 0x10, 0x9f, 0x77, 0xfa, 0xde, 0xf1, 0x2e, 0xb6, 0x43, 0xc7,
	0xce, 0xbf, 0x78, 0xde, 0xd0, 0x95, 0xb9, 0x41, 0x2d, 0x1d, 0xf7, 0x56, 0xa5, 0xa7, 0x59, 0xaa,
	0xad, 0x55, 0xee, 0xbd, 0x0d, 0x34, 0x37, 0x35, 0x4a, 0x15, 0x09, 0x54, 0x34, 0x1f, 0x28, 0xb3,
	0xb3, 0x06, 0x5d, 0x30, 0x6e, 0xb1, 0x72, 0xd2, 0xaa, 0xf5, 0x2d, 0x27, 0xa4, 0x46, 0x39, 0x04,
	0x51, 0x9a, 0x9b, 0x3b, 0xc0, 0x49, 0x08, 0xec, 0xd4, 0x4b, 0x4b, 0x85, 0x59, 0xa1, 0x7a, 0x8d,
	0x1c, 0x99, 0xca, 0xb4, 0xe4, 0x24, 0xfc, 0x57, 0xd5, 0x3c, 0x00, 0xf6, 0x73, 0x3a, 0x8e, 0x5f,
	0x79, 0x65, 0x89, 0xc2, 0x6e, 0x12, 0x0c, 0x2c, 0x7a, 0xde, 0xca, 0x1b, 0xd3, 0x6c, 0xbf, 0xc8,
	0xdf, 0x9e, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x67, 0xd3, 0x84, 0x5f, 0xea, 0x00, 0x00, 0x00,
}
